version: "3.8"

services:

    php:
        build:
            context: .
            dockerfile: docker/Php.Dockerfile
        container_name: php_social
        restart: always
        working_dir: /var/www/app
        volumes:
            - ./:/var/www/app
        links:
            - mysql

    nginx:
        image: nginx
        container_name: nginx_social
        restart: always
        ports:
            - 80:80
        working_dir: /var/www/app
        volumes:
            - ./docker/conf:/etc/nginx/conf.d/
            - ./:/var/www/app
        links:
            - php

    mysql:
        image: mariadb:10.5.5
        container_name: mysql_social
        restart: always
        ports:
            - 3306:3306
        environment:
            - MYSQL_USER=root
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=social
#        volumes:
#            - ./db-data:/var/lib/mysql/
