<?php

namespace Tests\Feature\API\V1\User\UserProfileController;

use App\Helpers\Test\TestHelper;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class UpdateCoverTest extends TestCase
{
    protected $token;
    protected $headers;
    protected $user;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->token = TestHelper::authToken();
        $this->headers = ['Authorization' => "Bearer {$this->token}"];
        $this->user = TestHelper::getUser();
    }

    public function testUpdateCoverEmptyImage()
    {
        $response = $this->putJson("api/v1/user/{$this->user->alias}/settings/cover", [], $this->headers);

        $response->assertStatus(422);
    }

    public function testUpdateCoverWrongImage()
    {
        $data = [
            'cover' => 'iVBORw0KGgoAAAANSUhEUgAAABwAAAASCAMAAAB/2U7WAAAABl'
        ];

        $response = $this->putJson("api/v1/user/{$this->user->alias}/settings/cover", $data, $this->headers);

        $response->assertStatus(422);
    }
}
