<?php

namespace Tests\Feature\API\V1\User\UserSocialController;

use App\Helpers\Test\TestHelper;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class CreateSocialTest extends TestCase
{
    protected $token;
    protected $headers;
    protected $user;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->token = TestHelper::authToken();
        $this->headers = ['Authorization' => "Bearer {$this->token}"];
        $this->user = TestHelper::getUser();
    }

    public function testCreateSocialEmptyForm()
    {
        $response = $this->postJson("api/v1/user/{$this->user->alias}/settings/social", [], $this->headers);

        $response->assertStatus(422);
    }

    public function testCreateSocialWrongSocial()
    {
        $data = [
            'social' => 'fbk',
            'url' => 'https://facebook.com'
        ];

        $response = $this->postJson("api/v1/user/{$this->user->alias}/settings/social", $data, $this->headers);

        $response->assertStatus(422);
    }

    public function testCreateSocial()
    {
        $data = [
            'social' => 'fb',
            'url' => 'https://facebook.com/example'
        ];

        $response = $this->postJson("api/v1/user/{$this->user->alias}/settings/social", $data, $this->headers);

        $response->assertStatus(200);
    }
}
