<?php

namespace Tests\Feature\API\V1\User\UserSocialController;

use App\Helpers\Test\TestHelper;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class DeleteSocialTest extends TestCase
{
    protected $token;
    protected $headers;
    protected $user;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->token = TestHelper::authToken();
        $this->headers = ['Authorization' => "Bearer {$this->token}"];
        $this->user = TestHelper::getUser();
    }

    public function testDeleteSocialWrongId()
    {
        $response = $this->deleteJson("api/v1/user/{$this->user->alias}/settings/social/9999", [], $this->headers);

        $response->assertStatus(403);
    }

    public function testDeleteSocial()
    {
        $response = $this->deleteJson("api/v1/user/{$this->user->alias}/settings/social/1", [], $this->headers);

        $response->assertStatus(200);
    }
}
